---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-controllers-flux-webhooks
  namespace: flux-system
spec:
  path: ./kubernetes/infrastructure/controllers/flux-system/addons/webhooks
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
