---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/default/hajimari
  - ks.yaml
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: hajimari
      namespace: default
