apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:2nz++LAOaRtF5i3rSviuYXUM6uTndmhwjF31Soqt,iv:3u2UqPN/dviyxGwaOY+DUZ+h1gBgAJ+MoA3cYfU2omg=,tag:LmyVgBqVhadoPSaUDLuztw==,type:str]
    api-key: ENC[AES256_GCM,data:d8xaRhM2u5QDdPnN+G46Os8Tl8NX0bvpt1PJt2UkeZC1GE2PJA==,iv:a6ZzXFBv18BqRtGkRt5nUkAS6fVWPER3Qyz92uolIiY=,tag:FJjbKtmFwsYKXsbC/cxJ2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbFVab3ZXUnBxZlIyWWd1
            TWRDM1N3U1dKbFlzT1lOdURGS0lhL3RWdWlZCis0WnE0SE5FcUVVczh6OHNHbWs5
            eFBMS0xnZzhqLys1bFhnT3pqZ1BxQWsKLS0tIFJMb3JBUndYOVR0SFI4SlEwZG9Q
            ejE5YUlOVG82UUM5dDdKeHdmem0xNUkKJ8L+/Rkb5mZWZ1UuviDYKn+syvGt9bAp
            ggLJpKeIay1evttu3NjnZubG4CfO3n8UHPY6KObG2MX3pOMsTD3H+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T21:58:14Z"
    mac: ENC[AES256_GCM,data:/K1JTKEPukmvgVOeN0av02L2OtuJ+BAoVmD3CvPmKCHd3ZP/dZZPalF381Ddnx7dMZG3DTRdeZe+oxOqaIyNBAVWJchWnUGWG47Bk2RWvvrD2ugkfNis4vbQzJt2mvAWQDTE2/U/wsJlDSP/rU7EyAE4rixVGW65SI7nZwaBTKI=,iv:3OAkHW7qudD8v7mOeCtbs/dERgmcSPt4yaSWceQunmM=,tag:GUoQglZDnfh3btG4sEGRkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
