apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:TuHv0k2kdHhdhPQKu/6SEm6r1FmO/123P6zZsUEX,iv:4u9oL+Zu99f17SP+RVsiVT+rMLW0FV/kmm+k8oKqGhk=,tag:agAEKvNypeeW2NE45z6OVg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:+us/eGz+AAzNunbu5PDiaBlnTDRpAAgvm2vROOFU9fzPIrEDQw==,iv:c6m/oIQEGfp4jOyWuMwShHiHye7kdWCi6TqkUHvmn+4=,tag:QpVKpWZwc6bS5NQeSxpCwg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:8UdT4iB4tzzjQbaX+136bhYxAA==,iv:iX2cvcuS4S8yK/XgDwOsbdRoJJIqgPqq1UofCnfEqEQ=,tag:toqs7UxjI2MYbQvnqB+vyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzb0FWWmV3ODRWR1FEVTYz
            cmRDbDk5cmxjK2REMzRMbFFmT0lCTzZnTWxZClhBRDI2M3VPVCtydVRkZTI1bjBo
            amlTZCtGVnNEZFdTOFU5QlRQUlpOV3cKLS0tIGRWZE9UekUyV01ydjhNK3B0Vnhl
            ckhwd09pYml4VW5YY2lFemx0MEpDZlkKw5CxSTW7/t2p3U7Mg79wNPtAijolfHXN
            SybdMJ5Kpptv/gWgU+fF6h53ow8pyiUTuvBidzEC7+bJ3zlhwRDgBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T21:58:14Z"
    mac: ENC[AES256_GCM,data:Qv14JCkTcMZ+aOilmmTgv6AduBKL6lcfE+PP9RrKFH0GOHKePxFT/e5x7/zjdvNfloSFTZoHA4KTfgp50yVdMPQoH+cEoSNZB3AMovYswSBrXQ8GFqZJ/BqXoCY052+Rqsnc5UvfrWhrrmEax9uHGsUfW2l2IhTp2bayzznaV1M=,iv:V7Y+ty6yWlQiVflxsJ/B6Sps08/Y04mJaIoSbfyZzs8=,tag:cupJC7MTCjqzKTgDfgwvGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
