apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:mfMEYgD7sKQeM+aSsfxXJefgjUIIw8aJq9FYG9T9,iv:2xpUMsjYtWRDWNlWXpESBArGJThtjpp/XOW5NfVveY8=,tag:s8cAe3vdgkMcp6Yv26t0VA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:wZ4/y4WIUjHyoX3kHDdSzo7nRz6xMQdDndL8L2sIX+0vbdIlAw==,iv:V0BT3oJnt7ct762uLG9LMA7X8tD/7bNNkBC0l1R2q5k=,tag:MFHuESz82SXpnkSpPVofOw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:YHy0StuF7JaVv7JLi4N8Q9Xnk80=,iv:gjN1verayocs+OFcVwKSr3Q0eTL6DYwjs+DfUPUko4U=,tag:cY24FtDR4yjfUa49LlzerQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YlpLQmJuZHJQWjYwQ1Ns
            eWxjTS81WkR2WitzOUFCSTg0cVFHWG5PNTJVCmZxa1I1UlZ4UVZOeUNPZ1VtVnRn
            S0pTWGo0MlVLa2ZiT2RpMHdZY3ZKWVkKLS0tIEwwMEhmSVBRbkU3TmdSUTZKNmdW
            Y0JSamlxTUk2TWs5VUN0TW9MVlhHSkEKPETNz7XnfRPwAW2f1rZPai569pN4B8Nr
            Omf/iGZ8NHlaNAzTEPdqRIqUn9bKYwh43LRZowf4qk+tFR2j8MiyJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-28T05:20:09Z"
    mac: ENC[AES256_GCM,data:YTQVzKT8Mky3qSeW4+uHsKrGlX3hCiL4No50dl8Zba+hddEvijVpyCoLu3aaybK52jQ60M5VPnOr4dPpFzDA9OPaa3WFS25IYonxjQuswQAqDlA48hR+vq7bXBSN/KZZ7R1P2dmZdz03y6J+SA4WmTljmw5RLLPRqgllyeatCC4=,iv:3mLx48MXIZXehliRoi3GdflO4Of9ljd7pzgeILADomI=,tag:uGkAbHWAB70dlu2FQ7ujsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
