apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:xjWJImpIt1ucTvUQPTU=,iv:17qPx5+R83f5cXj2AN5Y8s23GyGyIt3m1TMMBQWuBes=,tag:UX7odA/VwwLMtyROJ6ehrw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:0oJeQ4OgkvzwWO65FBdpT1ElIw==,iv:rVf3Sc3Y5BLNxD9kN5ZJaXi808Ja3sNl3KxB8ts2GcI=,tag:G9RYByMkGCWgH3u+1pVEUg==,type:str]
sops:
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVU41ZVd0ZVc2Vmk3L1hY
            M0lBYVRldjN2c1BkSjdHOWxHOXRnUjUrSTNNCmlzTVZJTDYrY3ZMQnlSdjBWZWZa
            TnFIcTVvNDE0MWxST1FXOFgycUpTc1EKLS0tIHNUOVAzUHdMYUZKTHdQRHgzQ05l
            RGxoVnNZSCszK3NMN3hCRHl0bjljb1kKNCrL0I2xSDE8XBMpH8BoZlbdHiYr29mX
            3HGZEunJ6UuaQd3Mi4tt5Ym8zU8rIl+LnEJt6Ngu90oA/h9Pi6lpig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T23:16:56Z"
    mac: ENC[AES256_GCM,data:Ol2yB1LLB+ZrDYx/sEZV8RCHUo+rEoUsxYAaVzlATPfkNzC8oIEISSZZN2//iiV2L3b2PrlmFoH4tb0H4J0dOdxaw7jDGWvdPrg6k5DFIutOfrDGExoLO/cAmeg6fFcCFEEAhqnsG/ZTvDAoEF3RkmENGEJ+hurYOySw6XsorLk=,iv:jHDJVm8eVmGzcuj+tRukZ7GF3A/DsJjQaxvXOcYTaVg=,tag:kBa0OTRbNIQid4gBnXdZyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
