---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ark-game
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
  nfs:
    path: /games/ark/game/
    server: 192.168.20.6
    readOnly: False
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-game
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: ark-game
  resources:
    requests:
      storage: 100Gi
  selector:
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ark-save
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
  nfs:
    path: /games/ark/save/
    server: 192.168.20.6
    readOnly: False
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-save
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: ark-save
  resources:
    requests:
      storage: 10Gi
  selector:
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ark-cluster
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
  nfs:
    path: /games/ark/cluster/
    server: 192.168.20.6
    readOnly: False
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-cluster
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: ark-cluster
  resources:
    requests:
      storage: 10Gi
  selector:
---
