---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ark-game
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
  nfs:
    path: /games/ark/game/
    server: 192.168.20.6
    readOnly: False
