---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: 192.168.20.8
      share: /mnt/user/appdata-nfs
      subdir: home-assistant
    volumeHandle: 192.168.20.8#mnt/user/appdata-nfs#home-assistant
  mountOptions:
    - nfsvers=4.1
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
