kind: ENC[AES256_GCM,data:xKknwmkE,iv:udvm06oaRLd4qWQ0taOm8aAyZSY4tk+UB7NwupkexCU=,tag:ELgGCd4HTS1tizmASOUKdQ==,type:str]
ansible_user: ENC[AES256_GCM,data:PKMGK553,iv:65BOgHsowsI85xtmJNgu6bomvPwELQ0FEHMwr7vNIvA=,tag:g/4iznZ1VHS6qzzTRgufQA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:NMflLWTI9iCR+71U8TtZIdO24IZKA4zL,iv:3rAt/YLaYGmoBdSjy4302lDDBAf8ueZRe4kMiH1ti2I=,tag:uqeRae/jjT5y5mPc9g2c9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUK0cwZnl4K3I4UDVMOG45
            aExiMVcxSjNlbmtjUkludFVWc2ZpcnRMNDJrCjZvQ3B3bExiYkhRRFVzMHpWbU1j
            TFE1aDRJanVWQkZwa3A0UzBaT1MydDgKLS0tIGRDSC9TUEFPQzBrT3hRZUUyU2cv
            STJTYmtiUnZnVVBaZGZsVVFiRElwYjAKDPWLIUNyT0VTUBJiuup5wh7oSzMNPFWo
            Pg3b/XrxkU9lDNpFdV7zNJoX0WhOkJ+qLohu7tanvWdAYjGRXmNKLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-28T05:20:09Z"
    mac: ENC[AES256_GCM,data:ofuI/jJHttvu+i4deo8t1CkHBirVPBke6p5xqU9S0rNOgQt4SzLoXXhj2p5bLyRyOF/7a+KH0JXuQ8VIiMIGEpdN29KdGaUuhvtld++xpMP0DW7ZMjPgmFiSFGgjmoWWW3iRjU3/vq19XsvREfhQsNC8f+RcQlpFEOVuX1xGU9w=,iv:Rs90gqovE2r5jvUodqDtK9jYYMgGRnUZHD0bb3dBQAk=,tag:wTsXCWSG+mI7TJR2/J11cA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
