kind: ENC[AES256_GCM,data:bX5kxMUk,iv:Ni71p95jr/eBRNar/3KzRDTQ2kXGK2ivAF4pKiz6LDs=,tag:cwTlnfnjy72MpV4D9/TSWA==,type:str]
ansible_user: ENC[AES256_GCM,data:/gfUtCTU,iv:Uy1CTulGUTZrJJEhSYsZV1nxXzOa4dcQLEXHKFZRstk=,tag:KApAh9sx70WRNIhbMGi0tw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:s86QI/shGNNz6jZme086ejYvoSdx1vx4,iv:vOrUnZWAEI9d5mjzdkoMYS3Uv0v496SWo3IFBVv02E8=,tag:YWZGyLKId7YMt9rNp6DQPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4S0wxeldHbDFUdlN5Z0NX
            M2pJYWVrVzNqYnIrdXNpN3p2WEdvbEorMmo0ClZsNlZ1S0c5WHZFRzV3TXdPRHVr
            QjNQWGxONitOelU3bUZFN0ZZZVl1T28KLS0tIFFpdkZhTGtFc0tzTnd4VnJLMTBV
            UGNOOVpRVHYwQmRWZVdkeVJBL3k4VG8KfAnVGSvrHloLI6oCJioSinmNxYe4clkH
            6AF2+kT+xEVeilxw/tn1H6Rjz/wnZZ1qUvvlZcYsb52fZ7TVJ4bhwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-03T02:04:00Z"
    mac: ENC[AES256_GCM,data:GYaLDsHCOdfc2s8oRNjBsSqAMEjky1Ag3hbJisuydphGMpdkZ0En8kW8q9BoqmHYAYY6zLTPPou/OpsTJbGnYogFYfAdeHp4NWWtPnoXPRLuf2n4AsVcUOPco8Rnb7iuymXxTN1RwS8q0WLNhcDgP3j5SoszooSgzYu81RTAJQw=,iv:wOtNIVbzcxu547T33Vd+Fq6KtwShJ4QpRFH6me32YQk=,tag:Mj31XU2NIFfwScjRAd5qXA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
