kind: ENC[AES256_GCM,data:zfFuaaCs,iv:0LTET5sfsJei+6tbBLFxzfbkKNfkn7Dnhh7TPUsl8c4=,tag:fUmyui6T0Abbb1kdxnwGzg==,type:str]
ansible_user: ENC[AES256_GCM,data:3bEHphnI,iv:clIPoQYCOzV/W+SQXHtlyxWMbfKy17634sEIeF7LdaI=,tag:rfrT7Vb255GHN/ZHRAybXA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:DhmZAIK/,iv:7Gm8J5lVa2ezLQcffiJ/oNm8dtmzQ4sHZHg5t/PIQPU=,tag:bh2EhjNAXemtMRYVmjIUoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVFNjS08zZnhFS0xNeEh4
            VEZpL3J0UFdxb2JzZWd5U3NjNzBieVdiNERzCldYZFgxNmxTTHJNZ1RnWG9zQ0Yx
            ZkpaOW01RWg1SFVlcGpRaXhMbkJ2SGcKLS0tIEJ1VXllUkl6YlFlT2xLTDN1THdY
            elE5M2hHeTlYWGZqaGI2QkFqZUt3dG8KYlqERGC2hsL44hS1sTe8+MtXzMTngsiL
            GBt4FaNkTCRfPXcCiwqZHNDvpm29GryOJaLTQd2tcLpMvSdRfUNWNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-18T08:04:22Z"
    mac: ENC[AES256_GCM,data:SmQ0aaxUDSN+iUOTfjqtNWBZ8FrOX3CuGHFzlsgPYYXbYaDd+tNsgYvDHbZJVVwskg20s82vDQG545mAfkgFkV1wPjzbj/4ZYnGbZfaFpQts7ajNgKkl/gU7W9V/12m8VoqhUtuuDBV0C1lAMzQBj8uFA8lJM3G2Ujk8b+P3mW0=,iv:UyCdXnGPFj5oO+62sP/nEFHdYJ83vdmeX/oBCiHCI9Y=,tag:TtrWaUAL1/EF2ZjRacm35Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
