kind: ENC[AES256_GCM,data:RSMfGkY9,iv:EGCZpmqet62o50Q5UT6dsLqByPk+E/gy272Uf2sWkN8=,tag:0T3NOjhqKNut+jmmB0Xgsg==,type:str]
ansible_user: ENC[AES256_GCM,data:YWe3dyzM,iv:p6jpUCkFRE3Ioy+tg2g2QkSMcl0Szs0STu17wvVGnv8=,tag:Sy+JgWXUhEFECsvLa/2L4A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:se6QbRNi,iv:DeAZSIrchtFFJ2m5MZSyHJvxQQyw9I/6MS5HEFdkJ2M=,tag:siyFAdZzMMIXxCkvg9mCcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByU1BjZ0Q0Ny84dUZMb1ox
            SHVDRTY4aXRhNkhxK0FsUzU1YlNhMTVhZlZ3CjZ0d3pTK1AvUkg4aVVGNDRPdWdh
            QmdJUFpmU0x5WDlFeFFDa3g1ZU91SnMKLS0tIGl1WFJvZHlTSEQ5QnY0Z3A3SlBr
            M0xXRmVQSS9xY2tXV28zWFNlOXlBbkUK39uFukX86EgfyJ9OmRnZwsMkMDfFqIt9
            g51ieG/reuFCNDuPRz5Yzz8rkg/692QHhG4d8QxoZ1Y5CN0mcD7Fnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-18T08:04:22Z"
    mac: ENC[AES256_GCM,data:dplNM+0FINWbWe17QvLLZLKzT7KgWxl7BDSjrVgSGq5WcbISkgFWHNhsnxqM8s4xzIhH/RXvNVjkHVB1YiHGSOCAZFc/7JCsbkhcu5k8mA6bXtbgPNUm9138OwHZI5FqQaGhfzikbmbDhkexuTazDcNLSEOU62faCBfidwS8a2s=,iv:TY7NOyrd26R9gkTar/9O16UMlY5kl5IfP01975tbkXA=,tag:v/3pC/ihe72FxdtG+YL8Iw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
