kind: ENC[AES256_GCM,data:rY3+YLrv,iv:iEHxi3U7s/tgZvNw0qXBNeztXVT8SW8GP4f2OnUv1EY=,tag:oRg1ckS3uUoHstsznq8u0Q==,type:str]
ansible_user: ENC[AES256_GCM,data:StUx1zgN,iv:QVmWrzsKPh2mrrTLew8L5C5CIzklFArMsGn8qraW8c4=,tag:uEIx/CRXUAPuUZg6c0Ma5A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ZZM0GUTjAWUy/NP3Q3zaH5GSEuTQjlvK,iv:jnEoS+j8Duc7jks4ToJj3JY+fviBmWN5m2WXYzXWMvo=,tag:ImKS64+KxDP5N5Y0EHoBbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOWpJRkxaTFY5K1poQmZX
            Q1M0ZTN3eEVVK1djTnpZWGFCektUQUxaRDNjClBLOHpXNld3RFpNcXBnbG5vb2Jy
            NUR0cFhZaXZCMG5ZckdDRGMzRWk2SUkKLS0tIDREa29MUFJjTjlxSDc2bzh1UE42
            TVJjU3RHd1VGTUVlbFlIMFdGTURMMVEKnXvoTijK6xgup7h1KzWNSeadTSb2NJii
            woHDvDLBxQsOkoFGOPHu9ulIz560yMaoJG5M5AFdzVmevFxLJFKYTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-28T05:20:09Z"
    mac: ENC[AES256_GCM,data:E6WX4igyJdDRPjSZCuGupG+eNXuiZ0LTCBWzstwiW6WDedlpY5krLI5+MYeRr8+EkPsSjrKQf38LPCWeX9XyZJbrmvjd3DO4HCfIW/5kb3Jyk68wDxZo5wbrnR1VsDe/lTdnzQZfyMwwjxefPxc79GOouztis+hpuZOLm89RKCI=,iv:OwCR/q/7SrIs2zvVmXglD3hoDTQyAfEQ7hgfAJodGbQ=,tag:w0fo1SXkUsgBzEzbSIVsPg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
