kind: ENC[AES256_GCM,data:1lYQU/CA,iv:NLHA7JWOjUmA9tf9SACSSuqBdloQNL83rErVaRsDOZU=,tag:XW83lpo5ACSXkMgyCSmqFA==,type:str]
ansible_user: ENC[AES256_GCM,data:0NXS2bsY,iv:2MNXTi0A6qTrc44nwtFAKentg6R1i0pmMISgtPidqbY=,tag:ljHQ4k0zdsSqRjEpxlBN8Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:H7cG6rlsyOIylqH4JWQ674DhX3W2JbkG,iv:agNjJ4Gv5R1yio2NsL8Y++B7N3bYNjU9eV6WAvAcBKU=,tag:o2GngLKdoznpD9T6Jb7Aew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTK3NmZFJpVzFza1hNNC91
            ZmxxU0QzRzF4YVEzS1BVc0tCUFM4T2JZUlVjCjhKT3VaZWRSWFZkNTdRZDRkb2ha
            bjkwbTZMS3RPdW1zMzZqM0tWWEVvV1UKLS0tIGt3TnhkcEl3NkpIaEhuUHVLS0Rm
            MFdUUXRySFBzQktvdVNFeUtNRUc4bzQKpmQLxwMMSnoOoKgPn8YYqVCdViVgGK50
            Gert2mk/fIFCV6H0sDTdKDlhUYPJHsn+n1ujsUeFTDbzbHaDFmOs7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-01T21:11:18Z"
    mac: ENC[AES256_GCM,data:1q+pBsKIJUBic00j8KnxfwbSXF1NihBnVZyOdSENS9lYwG0r7F5r3RKzPUGH0rk2Wq0H7CrazkkKOjmR28R93TrkgSoDKC+4ZORsOyPAIaS/wCLxOWeEZccd4to/VBnHJjE6Tr4dk2LP8s4SAw3eoAH3fNqkTivMfyJ7hcn8vh0=,iv:zid5U+Yjbp/cUQkMPxj7qZ0FTGZsiqaDGrWOWuFwOSg=,tag:hGVIFfMGCbdH1Wp/aBF65w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
