---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appdata-pihole
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 192.168.20.8#/mnt/user/appdata-nfs/pihole
    volumeAttributes:
      server: 192.168.20.8
      share: /mnt/user/appdata-nfs/pihole
