---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appdata
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: appdata-nfs
