---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  values:
    configuration:
      enabled: true
      trusted_proxies:
        - 10.0.0.0/8
    controller:
      type: StatefulSet
    ingress:
      className: nginx
      enabled: true
      hosts:
        - host: &host home.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - *host
    persistence:
      enabled: true
      existingVolume: "home-assistant"
    podAnnotations:
      configmap.reloader.stakater.com/reload: hass-configuration
