---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers-kubernetes-replicator
  namespace: flux-system
spec:
  path: ./kubernetes/infrastructure/controllers/kube-system/kubernetes-replicator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kubernetes-replicator
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
