apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:4L4Rfl26hkMN3d44Vb/Fc5IQKzHdCo5hD8y/XY2KrYuYQ8I83GozHw==,iv:HjLqLxUoKJtH6oy3yVvtjz0Xuyo9ifK1G4VH7j4dXMQ=,tag:jQChmR3ljJCQ7SC2Y2gi7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQc1pRSVlwV0pEakJCREtt
            RU1mRE03dlJhakpJaDhEK0NoRENJbFRQTDJVCmw3MzBOQzliL2JkekV0ZjFtQ3lz
            a0FzV3VYcmdyWGxRbEdvNTkyVGdudlUKLS0tIEszVzlLYkFCSzVvbWJMV0ZYZk54
            ZFl3UHRuVzFKVkptV21KNVRWdEQyWXcKNFK1UMOijemkGs7Buvert1ySTVDGpyeW
            SKfBLbjS6iHfgl8P2KFHkGzHcuJa9eChIk7Mj8jXSBAzS6hpCBvi5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-01T21:11:19Z"
    mac: ENC[AES256_GCM,data:as9LfRUSouTzKokD9qjj/OVRbzDLCJ4h+xf/TRj3Z4gC2gh8V0BdJhp4DHEz4anHbJcWCMpV6CVvPDxx6iPqEVVUcsRj3KoMxEl+HxuyaWYKz4f1Z5stFSam7LsUiarGyHgbDghFlzBhvPm/G/xPLzHO2zcL/f6Ej3EU/HDAFD4=,iv:bexH7Tc++r5dT5Gpmiz3f54hAxKQHP6lhpFsaj3c0M0=,tag:3+ruOCjLBP0AsEohlqdFXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
