apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:oZ6Z+vGqHxL7m44zd/+JO0PveXK+gYRQyX/NE16jWNyvwnT77mOHhQ==,iv:fZKoDaKH68F8rOuweg4a7Zv92xpeXfmM7KbKPjQOzUE=,tag:2t2MlxHjGOYbFwimOszydw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSK0VFeXMvMnd4cDc4bXJU
            VkFtdHFDaCszMHlpOG5WTjl6eXpEUEdGbjNnClhuTjhpZUdZdEtMcW5ROUxBdlo0
            SmNPMHAvSFFPOUdJSUxBeEVWcDlaNmcKLS0tIFN6UlcwYjVCc1RCaWRTdXpVdXFv
            b2lMSTBUYUZNMUw1M2NYTnphRzB6SU0KfJk4v1SwDgA+cjLeRqF7g/BiAs/aVvJz
            PChcsb5/LI3KARcNPtAWGscJodw3gVPvLWqgy82cSGVvqj5AL7DAjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-28T05:20:09Z"
    mac: ENC[AES256_GCM,data:E7pp6yGQAeAsPSelu6PuxjwzLw198bXN1iRL1299oF/k7hCg2u7gzLHEAoyEUe2oBQY9JXN4xoTiun4JA3hdPzh3QXrg2Ph2gnoyiNPR4pF3r/jcTaYkKVNQwpA28RfV0mkcuzsfR9s3s10d9AlKr6+AL0wd/vIkdiVhZ9us4kE=,iv:JJjs2FYaOHdjJuUDLQNxMPPiFynyYIy0CAVp9SogciQ=,tag:QVA5UvHPRF3pNIrdOfb62w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
