apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:FG9ciKRVXciFApHLxW3nnMjwBtLCAUh8mCLb2s1tQR/HLloeSCF9Zw==,iv:hL4+DP8MzlSeVvfbyibEa/2iVn5upZvJJfoO0SCUhVs=,tag:PhMWoukRqJ+yRSIpRfA4bQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L2pUbDNlVFlNVG1CZWVn
            U3hlVkpySHU2QlFIeHJncWY0UDdCYlhvMmw4CnkwVG5NWEdkYllCTng1cG9PbkNw
            SWV4WTBoQnVoa3lOaFlla2hLVEhaRnMKLS0tIEQ0UXdtaEJyY0w0UEdSM1dUVFhp
            L3ZtVndCTXRkaUliZCtCcXdwQUxXY28KtJxAG0PlwdWy6spssclG2+yuTeNFhlao
            Dny7zJygOLfUVv5o9sFV4c8/5wpRhmNi8lmpVYXyaUGfaSe7zvGiCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-18T08:04:22Z"
    mac: ENC[AES256_GCM,data:VUzZaysNCCkW8A2bH7CQ3cGHe0hqqfQYQCa0pLw2HS7CZIBFTfvnT673sKodTdG0gzvxhUHy05ex5Uf3WISU71iuPMUo54I0LqBKade60smjrMkp+DWqsmLEPRfObAR3CmogcA7qAJAfvlsWHobcZmMh7Hp9M6M3e2PHbbRTick=,iv:nwHn2PSaBrhHqr72rrVvV92tHXOkgtyo+Ixgr7KhdJ0=,tag:kRQqdtsgUJzmUFfBMfvZ0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
