---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  releaseName: vaultwarden
  chart:
    spec:
      chart: vaultwarden
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
  interval: 10m
  install:
    remediation:
      retries: 3
  # Default values
  # https://artifacthub.io/packages/helm/vaultwarden/vaultwarden?modal=values
