---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  chart:
    spec:
      version: "4.11.0"
  values:
    externalSnapshotter.enabled: true
    controller.runOnControlPlane: true
    controller.replicas: 2
