---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/default
  - ../base/monitoring
  - ../base/pihole
patches:
  - path: echo-server-values.yaml
    target:
      kind: HelmRelease
      name: echo-server
      namespace: default
  - path: hajimari-values.yaml
    target:
      kind: HelmRelease
      name: hajimari
      namespace: default
  - path: pihole-values.yaml
    target:
      kind: HelmRelease
      name: pihole
      namespace: pihole
