---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/pihole
  - ../base/csi-driver-nfs
patches:
  - path: pihole-values.yaml
    target:
      kind: HelmRelease
  - path: csi-driver-nfs-values.yaml
    target:
      kind: HelmRelease
