apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:v8X5C1Teg8+HCX9kPiwb8e+gnGmSKkm68QmMUqtE/mEn1/6+JQ==,iv:1JSuC5C5oGnCRlTSjLugGrugr2JyhIkK1N4qmniIB8Q=,tag:ZFy+ipWhVUSsssMsz1KXnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbXptOE01ZmdTSzhaWmNF
            dmVkRjNPbk1TOXl1UHNVNVovQjFMWVIrbmg0Cjg4YnlFdlFrN3RETVE5YWg2eHpz
            ZWJkK3hDcllIZXRIaFVSdjMxRVhwemcKLS0tIG5MZDlFSnp5c01vdFJEdEJLc1lw
            Yk11Q09hVkc3YUppN0FSbTNVSndXUEEKUoCoZ4UO7XXTGyoTXVff7oQGokuyxLJ9
            Z1mbTS/Lqgj3Hvpghmb/Nwwg6C1/mSBdG6OCYIAJfNo0UKJ10vKA1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-07T06:44:37Z"
    mac: ENC[AES256_GCM,data:M7jbnxWnYaPD2AwzXcxnY6FmrGlpvdqQ3E+y8an+iefeO5v4kI1nBvvasNflVjSU/vBABqLtEcZ+Qn0EtFhSw3HM8K+GGcbNEw+O6bOFDf5Vx7Rkr5bp+qSnfLuZmNYMNSWR+hlHv8rwYWQltGrYHos2UnA7TAziImn9Ol3U0nk=,iv:SUbT6mjBPzQyx2l6M1y5KI9/gylie7O0Hn85dlEsitw=,tag:A1ERPvI2mWSVNZFFr/vlhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
