---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-pihole
  namespace: flux-system
spec:
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: pihole
      namespace: default
  interval: 30m
  path: /kubernetes/apps/production/default/pihole
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m
