---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - /kubernetes/apps/base/default/pihole
  - ks.yaml
  - secret.sops.yaml
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: pihole
      namespace: default
