---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  chart:
    spec:
      version: "2.26.1"
  values:
    admin:
      enabled: true
      existingSecret: "pihole-secret"
      passwordKey: "adminPassword"
    DNS1: "1.1.1.1"
    DNS2: "1.0.0.1"
    ingress:
      enabled: true
      hosts:
        - pihole02.${SECRET_DOMAIN}
      ingressClassName: nginx
    persistentVolumeClaim:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: "6Gi"
      storageClass: appdata-nfs
      subPath: "pihole"
    serviceDhcp:
      enabled: false
    virtualHost: pihole02
