---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers-k8s-gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers-metallb
    - name: infra-controllers-metallb-config
  path: ./kubernetes/infrastructure/controllers/networking/k8s-gateway/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: k8s-gateway
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
