---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  releaseName: pihole
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  interval: 10m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/MoJo2600/pihole-kubernetes/blob/pihole-2.26.0/charts/pihole/values.yaml
