apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:0AloqhCwverZLJsKLzfIbmyrKpPudLMFWu+LNdg+wGAjFO8Orw==,iv:QZPgDt38+Hzo86iXenSKTc5Aagnkf9+u4zZSuLqbGbo=,tag:bURHWpSe+UNTfT/Jpvn37g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxa2ZCL3pScnRkRW55QVo1
            Ui9aUjErbkNpNlVEVE1ZNkJDWXg0NjErRUZzCjF6ZjJDQi9GamlRQWtkcFFXVVIx
            OFVRaDBBc2ZOeTdRWUpZQ0t2Sjd6elUKLS0tIEtYUFVsYTdJTjVicWVKek51WUJL
            bDRFMFlOQnU3TDF4bDdtZXJuTW9QdlkKwUTf6WlGATmBTATL2xKQuu+OOA7IrKMB
            LL4Qp6y61MDkb4IHmuQhbFJuR6ePKcGLAg6gD7mIE3BcsLdLa1KVJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-18T08:04:22Z"
    mac: ENC[AES256_GCM,data:ABxpMN8s+QHdRZ+sPW0oYZgcIM+FbXaOyUKq4zVl2wENExSTiXXF6Hh6RWAnx6JphYpIbtsohFkSroFp4o/gf5kSEez/YKUKlQUcivRc75rMtZj+5CucBihMbatcsmj+b2RpMCjDQuMnd2RzENK1CEVtEikZF3VpB+Cn5uPzyFg=,iv:WDd5QtkQEoehDw1bholJk4gPg03eMswOheKSBfap/Tw=,tag:shxCvjDbH+t+N/oVNb20mw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
