apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:yGekffZozZbt1ocnDv31JFqjjInWz3BpoFRp4RTP,iv:9z75rJ5Tgvt6dtdJy4uCdr+QiAOsELImjuwJdn1+Ahg=,tag:Nab0RqG8/jJmZoteNBeLzQ==,type:str]
    api-key: ENC[AES256_GCM,data:o7o+Sh6tXVJYTFm9hbb3UeAAOKZaGbsehKwWh641/YbnEj+yvw==,iv:esjPsw31WrtvI3BMn81/roSHCNSyVzp5pv2fj+Qqua8=,tag:Z9nruiIrQeOr+iq2fPSq2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNDhYZjJTWlE1aE1RQy82
            WTAyQXM5N2U3eUIrNzVWQnZSaXgwWm9EUHdFCnhTbFdEeURLeEN2KzRlSmF1ZjMz
            L2YwQ0lYczBaR25FbjJXMTVhdDRZYVkKLS0tIFJRMVNmQ3ZjWkZFYWlyT1R4TUJm
            VnNMaDZQSDUyOHNCVXFZbC9XZlNMNE0KqIxn7KMljsmRurnDyzuyaP3JKcgnB2su
            1+kpGyXarA77o5b3DKMnEntU4YT9a7XjdVZYuzmVKXBCms4qxc4HSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-03T02:04:00Z"
    mac: ENC[AES256_GCM,data:dPuBxJScSPURpwtBnWCvEYzoaKxMzTXUi48wOZGhOkOBczI6IgVY6UDsA43BnDTMNTn8jUjhJXTc29vAJEZZ+Uv8EFBBFpnPb3ggqBdBdTiK/+cTj2Adq4T8oxay0P8zgFRYYrtYcOFKhZEZqUBJSPO2hTG2Su9XiML8HJX8FqY=,iv:IwXZSelTBrOVTJeRkvIUAwIYvXWjDlevpWSeFbXpX3s=,tag:UHzMX6skjB5YCUY0aV8SOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
