apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:XGzon0zzgWZR9PvMPr1kjzzfqQ==,iv:6w/W6iJW+lXeDDta2nkcOfGsH8/iesVdV5re3TN5bqw=,tag:zSef1G51r6ShDMLpCgZDvw==,type:str]
    api-key: ENC[AES256_GCM,data:wt0irXY9uDw6fvEnS+GI9gtOS/4en0WwXTE1UE6C6AGQqCVPqA==,iv:qmCm9S72CYlytJeImoCWXEL8hvtAaS5nmIJBjd77wuw=,tag:bTk6hBSI5+x/0FE/WjcwCA==,type:str]
sops:
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbFRjdWt3bTNKcXBSbU5j
            VXVlRmxyVXBUNDFoenJFb0I1b013SEhIK0dNClpURG1pTTRIUHFqOWhkTEdreXVS
            ZFNqMEYyckxmWTZaSDNtR04vODd1MzgKLS0tIGxRRmYrNnRyTVV0MGVQak9ESjVu
            Y3VzZWUzSU50WWxjcUFkdi9RcGFhencK18TLDTIlGXwKmEq9eH8iW6x0J6HM2BRt
            94+SjdzxPZV176NcQAj2YzJxTlWOCTc96g+QARBx387o5MVSX8cKuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T23:16:56Z"
    mac: ENC[AES256_GCM,data:uT9DUK0+34hD8bZ35Y+lK4TapXFq/t7Vm6iz+KrSrTD6oQXKZxg6IVixf89WUnwUKgs+9OYLGmimcHUp/ppy74nVUSy2AuNgOwOlYm0XwEkwBbGATmnacJip2Qnz+IjqTUvUYcEOfiHbCwetyWywg0Wx0LHMJaigMuLO0fALdOg=,iv:eRCXf/YRcOZyiQx8J+ozPCpgirVN6XN1vvt3ICkYQ7Q=,tag:IjG5vH+qy6W3UrLT3SGekA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
