apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:Rvl6+h5Bm22pX27nUCvftySTsi9OgulPYWZt4DNMOAj0v16aX8718g4tH++C2z24aRyV+nUMbYFoAliW,iv:UyKhfI20lRbUMXBFIFaZEyT96NGVhl1LJtsG/ZU7u8Q=,tag:lzAszCOKbbDtp3StYuT3HQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVzRxVUJLL0svNkc0bFU3
            QVhGZGM5QkpBc0JWU1p0VE5aaU5URTdnc3hJCkVaQUFsN2JseVZMNEJGcE9Iam81
            OHYrVHptNGhSY3VNeXYwVWUvVk90cTQKLS0tIDhXTE9ER3R3cjhiVXYxeTdUQzBK
            OG9RQXZ3ZTN1QWFGNjU5QmRkYjI5R0EKgj/kC6WP7bEP7nllAuKM3iFB8CXYV+j6
            Y2D3C4qeBZl4lqFWWuHAuNaGcwRQ8qDtdhRJLBsFhICjYjxDESgNsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-06T03:05:59Z"
    mac: ENC[AES256_GCM,data:Zolyr0H6o4PyXuFXEYA38391gWFTe/gCTgbUGfjohZzieJm3um2ic99eTDPEk+doDfkv4r0+8ZqCQHJddTzUk+FErHH503Pwr2/jCQSDS8LA5fAshjcBPKdQcIwTFSLWn/0gqSQLrZ0U7YLYtS7uFVuzwp02chgTM1ot6t4A+G4=,iv:eMDGTegDoc3OLtbsBore+e1DKKIn4GjqmPs2KQpr+WU=,tag:VoYpTLP+NYiDuaWAy/aUAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
