apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:vnpxfmh7ysBJpYlkjtFN,iv:9B8j5567snhlcIS7gtAnKILP3bQo8fCi8fXf9nNXZWw=,tag:39NnwXm1d1iyaIrwf/geUA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:m/+l/ovmqqVR4g9I7mZVicTUHL3GARQt6ep4Cp6y,iv:2IR6WxPmbmMn46i8bGz8VIvvzZRn0VorQ6h6qZV2U3w=,tag:n+6dpv5OhoFUB679kHMGgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ1BTblVjSmplVFVvQTkz
            RXpMa2lQaVlyT0paRTZUQURSemxEZDh6cVdnCkFabG9wM0p0NEpqb0owRG5BME5k
            aG1qZ0NpSE15bEp5dnlyaWpSS0tLQ3MKLS0tIFM5SXZlR2R1MFVMNWlwUWNGOE85
            WWY3VzBnbGdqUWoxb2w0YzRwOU9UZjQKrtQEYxhMgdZxknv35UE6mPEzerA7LuqY
            KXq3bzfaC2vDNO7q64lG4ir3b810oWu0eLZFiucaBpgJJ0K83nzWvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-14T23:11:58Z"
    mac: ENC[AES256_GCM,data:gZDHNtzfN2BOXuyFeHLHXU7SwU6bg2UEbAMq4rytocDz4n4OOYO8VQMXqN7152tN7ylDZIgzHXsq0USJqYpki5c4mejclLJpwV5ZOObC1UURQRVYZvXGqGj2MJw1s4B9YZfTSSBdjQ9Iq2jyW1kMinyl0yPmp/HUWfCo+y8felg=,iv:ULIi0RMWgfU4PGXVgvb4OFLBdEVRmOtAnBmoKKGsXdE=,tag:FUepV9/+cXwKi0PVUEIltA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
