apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:plxpiq81xcoyiGn9dAtZ,iv:SzmhjaqbzNkszVZbjQpkl5ftLRhVNO4wv7t57MZoKH8=,tag:oaB93K4kzBUDalrhQt1DwQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:zMvZXmM0eOynmmJvzupL84vpCQOgI1191VXRUxHb,iv:z//ynd+oztYTDGlktD1iQA9WIGQG6q+ZkcvykZudhNQ=,tag:tVkOQWtoouqp9d0ZaH99Og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRFMrV0JySDhYZE5FSzBQ
            SVZZcnV2ckdBc2ZHbWVRem1qcG5sTzJKbm5jCkRGclRONGVlVi9leUExcVE4VVRi
            NXdVVVVVVS9YMWVMOW1WbDVndmw5aVEKLS0tIHRab01ISGppenYrVktyVVZJREJO
            cGpnUDI5cjNPNUM1dUxGbE5lNXNlN1EKP8T8u9tKPcwqzsY/eesIA5JREV+ynVnX
            yOAuiaDM0NB+lFW9bJvxJxUsBlEpGEZrwHORcR7JY3uk74P/TXK9IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-18T08:04:22Z"
    mac: ENC[AES256_GCM,data:vuLq4B4MByRauTjhBB135kk5CyXAxPw/OJQCwtZojVi+Po9v3b5OgnJGKs2bks88kgDNVAGeq9TRHoldkIsq1skQZH+Ciq8ubShB+pmpsC4mEzWIjGkmVR82bfA18aUwIzBiIEOuYzEe+G4REabhF0NkymbnFP19mHEmKe/nsNQ=,iv:F1FSb3eADvJi+0vRX1N+s9WiMOjQVGRl/DvX2kcluGs=,tag:IPpjVGomhUL9EUzbN2rqKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
