apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:DIIwAJZB2iVxM1SsOBw=,iv:gLszPlqnqChpUX9S+4cV7Fz5NDd0fjEK6GRhyk5+pdw=,tag:ki82JRmqHOfri2oTfvRUHg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:FiYQ5Dv0pzGe0Cp2JTnAvFxt+zbT6+pX7FbTdxFN,iv:di4A5pJg9upiS8YTCCufSIwL6jKIJgFmXrHzkkk1N+4=,tag:jhqkt2hKXSBiYg1bhQG/+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTXN5RTJiMElOMkt0VjBp
            eWpIK1RTZDRVOEs2SmRweVRSL2VpTVZUMHdvClpUdEdlNEJuT1Z0enBJRC9ZdkFQ
            WExTQkVCUk9ZMURBbVlTZ3lKc2dxTzgKLS0tIDExMGtUWVAwejRvdVdjd3Z5QVI0
            VDZtRVlyZEt0RXVUR2hZTGZiNlRLQkUKA1aMODwzXYWNHUQDCwj4wlEPFZTjwuJv
            5akpb1gPJtqlu4RzDU2T8FYTLp//u4DUQ6d+Apnwd4+RlZyx1QYjMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-06T03:05:56Z"
    mac: ENC[AES256_GCM,data:8WwWuvLcNSgcUBKjDSGkNrPbsJRJ9yImBMPUy3H21OEtbWc4B3GSJnay1Pt0/dXk3sP3qkw1nxadrwarw2DJNPwKryGIFf/0klM5XRLLGu/o44l8+bNRalENhyRA2eB9kZsjjYl8jNo5PWRSollv5oIQ8XJp3CYHjIteBGf2wZ8=,iv:9Xl+PuTFPCF8DjI2TJ/Ql2U1JNl2XvTfAdtQb0knDUw=,tag:FmAA8kdp/3gKAThCjPHySQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
