apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:jin3aSVKa1RYuFy+3x4=,iv:CVGyOrFqxBKqkUirD9O+cxpzxLrMjPi3p9u29G31Am8=,tag:aRdsPpHtePYBTCKiEpue3Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:xj+YHYYW5pyu9dXtBv+Pegx6rYOqS6BznGGR/muH,iv:hhWio85DMJdFCmAUP3ronUJJI9sFgdmC05/s1stHCcY=,tag:MEixI3ynKHRtkWpB6s+BkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVjVONTFTZCtwUlBHcElG
            R0NuZ1Nra2VQN3VvaUkxdDZMMjRnZlYwcDFNCkN0Z0EvbHpnNS9lbi8yVHQrZm1V
            d0JiOTZHcmprZHB2V3hKVXJLNFdxaTgKLS0tIEJTbnB1V0NuYzUwRGcwYkZUNXdr
            RFNCMEd2WTcxK3lUUmI3bVdUUFE3cVUKYsF3tQgXh9RWX/DVccB6iq1hy80cM55M
            FAOqXJ+LxfYzhGbIv48h0FznGcw0vso+M6Lp/dcSO3jymer1SCgbow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-03T02:04:00Z"
    mac: ENC[AES256_GCM,data:SLRffNqaH2Fw9+YqGFEBMajx+dZCeTFsHIw7B4dF/58Wuxheb/kn+iH8J9aTpUQERpVArdzzyFYgRUr+9vq3xhIW72L+9FL6YVmvj6Pv68zjFGsxD+yy52xVTmAy/wnqoDdL8GXwv3pctVpTQJywrlh0E+JtSexi6eEgkR76QL4=,iv:FLEAAWBvbetWNqbSfIiW62x18ldfXyVYTzovXcjHUG4=,tag:qquznXX/BAFrz07TBGJ0Ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
