---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-mosquitto
  namespace: flux-system
spec:
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-age
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: mosquitto
      namespace: home
  interval: 30m
  path: /kubernetes/apps/production/home/mosquitto
  # postBuild:
  #   substituteFrom:
  #     - kind: Secret
  #       name: cluster-secrets
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m
