---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/home/mosquitto
  - ks.yaml
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: mosquitto
      namespace: home
