---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-data
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: 192.168.20.8
      share: /mnt/user/appdata-nfs
      subdir: mosquitto-data
    volumeHandle: 192.168.20.8#mnt/user/appdata-nfs#mosquitto-data
  mountOptions:
    - nfsvers=4.1
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: mosquitto-data
