---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/default/vaultwarden
  - ks.yaml
  - pv.yaml
  - secret.sops.yaml
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: vaultwarden
      namespace: default
