---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: 192.168.20.8
      share: /mnt/user/appdata-nfs
      subdir: vaultwarden
    volumeHandle: 192.168.20.8#mnt/user/appdata-nfs#vaultwarden
  mountOptions:
    - nfsvers=4.1
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: vaultwarden
