---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers-ingress-nginx-certificates
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers-cert-manager-issuers
  path: ./kubernetes/infrastructure/controllers/networking/ingress-nginx/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers-ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers-ingress-nginx-certificates
    - name: infra-controllers-metallb-config
  path: ./kubernetes/infrastructure/controllers/networking/ingress-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: ingress-nginx
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
