---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - /kubernetes/apps/base/default/echo-server
  - ks.yaml
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: echo-server
      namespace: default
