apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:A6vvCBWirk2nnH5Peew=,iv:WbS9yUhB3cIWu3vbwDqAKAYvHn9FzWWe96ZEoIAOsQU=,tag:ZBUn1N2za6jyMN6fvCB9mg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:kSH8+BbU359BNEf0/VdBJWP94C2zJNA6Ln5AVGp3,iv:3wI3+f1mD1+CyrBfnPgBGFhhOF7q+ZH5jsaa6UBnzw8=,tag:OY7b/96QeAbppieN7XNduA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xg3jzrkt5nm2dl745lalrwsefustjrkw2zpck54hrc0vwqw2rsdsf2zajj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5c0daUWpDWGtUOWlPUUVh
            KzJZa0pXZ1drcVdtQTRqQitkZXNobnA3dEdrCnJYdHV3azViVFUvd0w1OHRQN2hh
            MzY1aXo0ckFsdXV2STZ5MFhOTjN6WkkKLS0tIC8wNTR3SGZNT3d4ckNueUswV2xS
            N1NLekoxV3lnMlFuUDYvaEJJZ2N3Z1UKa6fWwW4xaBF0oaaq0c0NmuXrvf3Rhm9W
            8UqwaQQcMstdOJE2l+vuMP5V0bfIyl0yVT+PzHazCJUS1Ox4PRj8rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-19T09:25:30Z"
    mac: ENC[AES256_GCM,data:gXQUU6OMiyGdzSqePn+m4BJpvWfJOpi60HimFSRzNCE2shtScDZpbqnkEzrp/U0mrx5XUnIKHCDN7TBxDUeJE5Pwvu3VbjStve4M19kUII+2T5sqU8MG5Aa93B5qHbxcxtYPb/HX7ztVYP3rQ/fH5j7SkYeD08q0fL78kI3V650=,iv:YuT04hXnwRWUFTdftWtjBijdWqY5eNDjRa17BgCokyg=,tag:7frifxjx/W6dK72xOkbH1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
